<?php 
echo '<h1>create</h1>';
//$form= $this->form;
$form->prepare();

$form->setAttribute('action',$this->url('user/default',array('controller'=>'user','action'=>'create')));
$form->setAttribute('method','post');

//var_dump($this->formCollection($form));exit;
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

/*echo $this->form()->openTag($form);

// ...loop through and render the form elements...
foreach ($form as $element) {
    echo $this->formElement($element);       // <-- Magic!
    echo $this->formElementErrors($element);
}

// Render the closing tag
echo $this->form()->closeTag();*/