<?php
// Attached jQuery UI Scripts
$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('/js/jquery-ui10.js','text/javascript');
// Attach jQuery UI Styles
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');
// UI Initializer for buttons
$this->headScript()->appendScript(
	'$(function() {
		$("a.ui-button").button();
	});', 'text/javascript'
);
?>
<h1>Welcome to Users Module</h1>
<a href="/users/login" class='ui-button'>Login</a> | <a href="/users/
register" class='ui-button'>New User Registration</a>
<table>
<tr>
	<th>user id</th>
	<th>user name</th>
	<th>user email</th>
</tr>
<?php foreach ($rowset as $row) :?>
	<tr>
		<td><?php echo $row['users_id']?></td>
		<td><?php echo $row['users_name']?></td>
		<td><?php echo $row['users_email']?></td>
		<td><a href="<?php echo $this->url('user/default',array('controller'=>'user','action'=>'update','id'=>$row['users_id']))?>">Update</a></td>
		<td><a href="<?php echo $this->url('user/default',array('controller'=>'user','action'=>'delete','id'=>$row['users_id']))?>" onclick="return confirm('Da lizelis stvarno da obrises?');">Delete</a></td>

	</tr>
<?php endforeach;?>
</table>

