<section class="login">
    <h2>Login</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as
            indicated below.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller' => 'Login', 'action' => 'process')));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('users_email')); ?></dt>
        <dd><?php
    echo $this->formElement($form->get('users_email'));
    echo $this->formElementErrors($form->get('users_email'));
    ?></dd>
        <dt><?php echo $this->formLabel($form->get('users_password'));
    ?></dt>
        <dd><?php
            echo $this->formElement($form->get('users_password'));
            echo $this->formElementErrors($form->get('users_password'));
    ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
    ?></dd>
    </dl>
    <?php echo $this->form()->closeTag() ?>
</section>